### ISSUE TITLE
I'm getting 'Cannot set property 'messages' of undefined'

### ISSUE THREAD

**Issue by tiriana** [rtfpessoa/lesslinter#1]
```
/usr/local/lib/node_modules/lesslinter/src/lib/lesslinter.js:47
      lintResult.messages = [];
                          ^

TypeError: Cannot set property 'messages' of undefined
    at processResult (/usr/local/lib/node_modules/lesslinter/src/lib/lesslinter.js:47:27)
    at LessLinter.lint (/usr/local/lib/node_modules/lesslinter/src/lib/lesslinter.js:36:23)
    at processFile (/usr/local/lib/node_modules/lesslinter/src/cli.js:174:33)
    at /usr/local/lib/node_modules/lesslinter/src/cli.js:300:13
    at Array.forEach (native)
    at processFiles (/usr/local/lib/node_modules/lesslinter/src/cli.js:296:15)
    at cli (/usr/local/lib/node_modules/lesslinter/src/cli.js:400:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/lesslinter/src/cli.js:417:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

```
$lesslinter --version
LessLinter=v0.0.1
CSSLint=v0.10.0
```

My node is `v5.0.0`

**Comment by rtfpessoa** [comment]
@tiriana that happens because it could not parse one result. The code should catch it and apparently it is not correct.

After the lesslinter I did sslinter for both sass and less, the code was rewriten to better accomodate the two can you try: https://www.npmjs.com/package/sslinter to see if there it is fixed?

**Comment by tiriana** [comment]
@rtfpessoa I'll do it tomorrow and let you know.

**Comment by rtfpessoa** [comment]
@tiriana any news about this?

**Comment by Kolyunya** [comment]
@rtfpessoa I've faced the very same problem. I can post the contents of the `less` file which causes this error if it can help.

I've also tried to install the `sslinter`. But installation failed due to https://github.com/sass/node-sass/issues/1484

I can provide any debug information if it can help.

**Comment by rtfpessoa** [comment]
Hi @kolyunya. This project is kind of unsupported for  a long time. Since it does not give results a good as it should. Probably you can find one native less and scss linter. 

If you want to you can also do a pr updating the dependencies. I can also send if I can. Get some time to do it.

**Comment by rtfpessoa** [comment]
@Kolyunya I just updated the deps in both `sslinter@1.0.0-alpha1` and `lesslinter@1.0.0-alpha1`.
Let me know if it works now.
